### ISSUE TITLE
Mailing

### ISSUE THREAD

**Issue by ryanlyrl** [cuhacking/watershed-backend#19]
The API needs to have mailing support built in:

- [ ] Endpoints for sending mail
- [ ] Password reset hooked up with emailing
- [ ] Email on registration?

**Comment by dellisd** [comment]
We'll need to figure out what mailing service we'll be using for _this_ particular task, but are you thinking of making a mailing microservice that runs "independently" of the rest of the backend?

That would maintain some of the "modularity" we wanted to have originally, but I know there's a bit of overhead involved with that.

**Comment by dellisd** [comment]
We're going to use Mailgun for sending out emails (the account is already set up). We'll have to modify the user, and possibly the auth, system(s) to support "confirm your email" type user flows. Of course, we'll also need to handle password reset emails too.

Other than that, most of our messaging that would normally be sent out via mass email campaigns will be done over discord instead, so we don't have to worry about any of that.
