### ISSUE TITLE
Assign discord roles for users when discord account linked

### ISSUE THREAD

**Issue by dellisd** [cuhacking/watershed-backend#23]
Access the watershed-discord service and assign users their roles _after_ they link their discord accounts.
The role(s) to be assigned should be configured by the configuration file.

This should be a _separate_ endpoint from `auth/discord/link`, the reason being that users will need to accept the code of conduct prior to being assigned a role(s) so the process can't be entirely automatic. This also saves us the trouble of handling the problem where a user wasn't a member of the guild when trying to link initially.

**Comment by ryanlyrl** [comment]
Resolved by #45
